### ISSUE TITLE
feature_util has issue 

### ISSUE THREAD

**Issue by aminemosbah** [izhangcd/DeepHF#4]
[~/DeepHF/prediction_util.py](https://file+.vscode-resource.vscode-cdn.net/home/msi/DeepHF/~/DeepHF/prediction_util.py) in my_feature(df_model, feature_options)
     45 def my_feature(df_model, feature_options):
     46     feature_options['order'] = 1
---> 47     feature_sets = featurize_data( df_model, feature_options )
     48     inputs, dim, dimsum, feature_names = concatenate_feature_sets( feature_sets )
...
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?9a9c1d87-2b41-4d66-bbd4-c258c8803f05) or open in a [text editor](command:workbench.action.openLargeOutput?9a9c1d87-2b41-4d66-bbd4-c258c8803f05). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by izhangcd** [comment]
The problem might come from the Vienna RNA package. Please make sure that the package has been installed correctly.
